OVH_ENDPOINT: ENC[AES256_GCM,data:N7qlh0Yt,iv:6owdgkXU17hH20RNow7j1hcntNaMYVh/AKAaAJn+3MI=,tag:sKudBoFWnzjXjD+DiJE0AQ==,type:str]
OVH_APPLICATION_KEY: ENC[AES256_GCM,data:DObW4FCas8PhsPWloDQPUg==,iv:QNX9bmmiHRclfoHXAJvfGKbzHpkTjnBUQhNQNCIkjW0=,tag:/MeuJunVtimeIbNNODHIOw==,type:str]
OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:mpMuCmlxIGcRKa6oC8QhD3ET6kSPvxrzdznYEKkkta8=,iv:1ddoc+mbvcsfOPUA8a5gzmhyQPvTGacwFk8Wsis7w0I=,tag:X6GYPEqSEPk1g8jdJw6VUw==,type:str]
OVH_CONSUMER_KEY: ENC[AES256_GCM,data:l6sBTy1DoylhGXNlgWIeDwYSNIvzAlAE0rwhCbLLm8Y=,iv:DZlPRkjDUqKu/WY+x9yO0XbbWBTP8uf8OeWkB7ZRJUY=,tag:xxQpXyvEEo+E7RX5hvF6oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDBNVVFVcE5R
            czVlMnlQd0xHTE9QMUJnTzljY2pPak5KTlh1U1duZ1RIUGt4MG51QWY0OFlRQmd4
            eUhSL1ZZalc1TDdQcWxKd1hFeElVVVIyNDBJMGdPRER6bWM3ZENPNXpQWEhWYTE1
            Q04rZ3hIbnRzQ2FrNU4wOStoM1FMdFMwWS8ybjk3K3JhM1JTZjRxT0ErWG9WQm5W
            cFlybFF1dzdBSkE5b3d2d1p1N08wZGZHRWdUWUFGeUR2NFM3U2t0MlpKdWVCUjc3
            RVczTkhWMUpWZmQ0VkFBYmQyOFgreTBTTkFsVEM3SGtJQzNPTFhvR1lHOGlOa1Jn
            SnUyaUQreS8vK3pnbWZYRGxJMHFIVHFjTWNNZTdLQ21MWmZXODVDNGw0UnB6dHVB
            RE1nanBkS2FqOWZUeDYwc0FpSmlNUjZQYlQwMit4eldEbWlubUtHZE5IdTZrZ09Q
            bWd6czAxNGVjRVlvTUFMcytCeTBSekxOQi8rM2hKTU9LQUI1allyUjVmZmo1WVNZ
            UWdEWjFPR2JCRVhZN2VvMzJWb3BXRllPMUM0UEVKMjhGMGkzOEZ3cDJVR043cjV6
            a1lLYWM5MWtlWTM2T3Y1cTkyUWJLYW0zb3p5YW0wanl2MU5sejZYMlExYVIzL1o4
            OEthTjhldU14d1JDT2gzSnJLLy9FZ2hFTWFhZmpsZWlub1lLK1RxOUdjWFRoUnZN
            ejJ2ZUc4TVZ5MWdDTXBNUHZ5eUwwc3Ryc2dQYXBkZ3VOMG5aL3NZUEp3U0dTYlpF
            bkhDOFNqRCtYTGdKVDNoZlpwUUwrWXBFeFVSUFJFQkVqUmd6UWtKQTdkU3BJcHhN
            SzQvcUtCYnVXT3JSRklmdnVkRVVZaWxEZWJTK1hZS2pFSzJ0VHQzOHJ0OTFORW9m
            RnZ6aHZtaVpiMG9jcHhHa20wclVaZ29GektzbWMydTBGRTBDQW9yTWRwVE13N1pH
            cGNES2xxMW5OUjVUMllSV0I5c1BmeGlQRkZxNFpZN2dDU2M0Zmp6ZE4yU1BCVE9k
            N25Ud0JZVGxob2szUWZKdzQxQzZ4VDJTUmFubGZTS1BlaTZBZkxBbnVKRUdLNzlI
            eFlQZE02Vzcza1MrckY0USt3aC8yWWkzNyt6MzJNQ2Mxci9ibUVpVmRydnFETjBk
            dmVqVUlUa3I0eUx5R1pQaXpLc29YUXFTUVZlcExZcUhtdjJUNnk5WmNBVWE0ZHEz
            cnlCWHBjZ2NBNzcrcHZJS244Y3dFSTY4UUlId2JNSi9EcGk5QTczTG1TazVWME1C
            UmRmWDE4RkZ6U09PY2swcGhkakhIeDhjTU1uMVlwQW1NbVo3NTErYUF6STJLNENw
            NVk4QW9NVnVNYmpoZkdFdzJ1WGozWUQ2ZHBNQ2owVXo0QkhLOEk3L3FGNHk4d2VD
            d1dhM3pGSGZrc0djS0lVQmdERjQ0aXY5MXUyL2lRWkFaMEprQk9wZStmK1dPWmls
            SU4xOTVkRzNoZ1MycWpYUHhYV2ZDTm8xVmlGVU9lQXNQMnBLYmtGVUI0eEtDZEs4
            eUdjczVFcWtseGYrN2h6WGtueFZ4R0RQNEprdFplZSs2TjhSektlSXZnd1JyNStw
            QzBWTGluYjRoUWxscVAzQ2ZxRmY1a2llVURFSmNqYWprTHBJRmZxdWdSSVZ0NjE4
            ejFJSHg3TnBkOGl2NUVUZWtScmVIYS9yMDBHd1psNFljdS9NQmpUTEtlc1NvWUhk
            SHl6Sy9OUitiV0FsemtrWG9XSzN2a3c0a05hd3gvVXJlL1lZcVBLWXpDUGxZUEJa
            ZHp3WXpxaEk5RVBQaEUveXQ2Mzc4Y0d2WUNsZ1lrUjk5Y09lUkRuNDdQR1AxTytQ
            S3VUM0JvT0NUeG5idTFLU0pMUncyNjVsUWo0dGdXUnN0YThlY014S3pHenBIdnBI
            YXVHSXVPMFBVdEIwT3Q1TXp2Mmw4NmhHWXVmb29wdWZlZVVIa05ESVAxYTdLdwpq
            VUhYWHVnRzlENGxkclhvUCtGSDVoWmZRV3JJam9kRytUd0orUjNoOC9rCi0tLSAv
            cXNFaDdPSUYwaUhxbVVXZGtOWmxJMnYwM0xQUG5ncW93V0pRbzc2R0JBCi8gZ+gv
            /Wz8RKO5a/5HGfypnvK8XkMR1vj1A95xLmhRbkyD5R6InHZfuO7zj+pt/UXqe25V
            DO5TgWiR5UEWy9A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1tq6xle95dfwwywa9ffzmzcecfaqcepmfehpprsxdjcaghcqysj232gjxe5hep3cjqs6qhwsjt0kfv7j2yhq6ke9cj6fdtqd8yq46gs9e9qzjcvse598sx3k99yd59fe9rkz0fyh3s43ycnrsshw2pffh9dfmxxplqyu7c0rhvtdnrrlzya3qfd4d0vkks4nyzxcj7zn6ynlh57fdhz3t8et52x938gxecaheyrammjn5p3r6cjft6s69xw0qqvreze2vm9f57w7vvklcsa0d5payw56mjj50wsdy4u46qu3r0ge6q0z675elvdjq0q94krcc5n6ampq4l27tr7vq2e2gxhqdfqxhgy2zprrm2zn2fhhtr4fjhf5yngq8edz4jfc9nwhcz4gtdgaz3qqvc8xxs6n3nxemge8wwu4muszz2fwrq6sfqd8kneqv9x987gdtlgeqra24f0uhhkf450u79z9rn3xfzu6udnamx2lrzuv2sjuejlpn7ap9n8ck0dd8xkhfz6r4g45gkc5kxpdj0upuyx2t6ktr0z9lsnyscxmm5umay2cg74fa0938mcp6kahpjs5xja6z7ucchg58uy3n4avhsc70pdmwp28ypkzqz09tyq2zxqvefzdgkef3f3jmv8zxs78jkwmn58neuy5045p7ncfxvv4tzkzjyvn37c2uwcjrdcn5t7qq4f9s2sz0ngscfqkgrrc8yfcuggtsj659kpalz5ek3gsz86vv4d4twpn27kks5ue05e4j2ne6qgruz6tn42uuevekxh3nnhshcsyx2dprkkguelz6acmkdnutygtesjdrp9shk5j33fetrt8qzft6xekv0dlv0jxdzusru8mnn7hj4g05gy7k9x2etkuqatz5nan99nj5xwupuhplhfktj5wppuzqzyavq7hpgcfzs2mvaldkx9fvd9h6vdq35fshzm9tv9c8qlhfk2wx7ag79vmuwunv5593cpmxc9r7t0zfp979c3ef2st8j8uqzrpq5wgm3sqrxzaryjdmz2yyc8p6t9y0au32fcch4pl6xudl22ut8dvhzc4e62g2pa5kcfsshwqjzz8hfa20q5jthr24cd3229c7pvvxs79zdwdnz3x34w5gghw8w3pt82g362wq36wnrsp5rrseeygf3fpkvau4s08z4t69w6gqlw5vddq72pqpp0n6dl85g9txza54g3ewd49fdul4cq0v0z0equm8qeu8r84f4j384tqk2cg75x2qwcjn8cgj40aeg0pyv7tmvs2s34yh2dnfvujc072hkzt7dnz0fsfz4l33muy2pnqccqrcw4k6kcyarkdsdwfq503urscgtwh45dn93kvxx39vhjnkgvqz32sdpfp8v7p6ew55jjge5mhyje2pgg4hdymq7ts3j5n2kwn60qcctqv2q8vcv8pj2zjer0rmuds80smp8695v3vh5ewhkzdfcum3ayvsv2zmuwsk4w5h094adphqj2g9vep8a5j5svzdhjca7srejejw8xdrhma3zy96dtxvtwyyswduy2c5jtfgvef8fxv7aqlgc6unuqmnd752gt5xcy7zvdhujhy5dqcyl7tqjag4g8djkxxafzzd5a22zj2xpea2sv5lx5yzcnzsjjvz23kvt9y0whn7zzdrx5am9v6ms8ffhmzpxn7wj4qvhdz54e350mrp29ysq2cgx42sefnpqte5fyxyhgneynwmtrrv3q6pkkdgul49s77g0qst76u3s665gg46lv865g2jz2er8dk0udd47fwyh89fzfr0tysl2xzq353zra2p3rysdwpmw4gqw32ua5mu2uygwhymtfe9drwmt0h34wyqt9uz7led832c5s6x6a8pfpkrrs2cwkdplfwpu6068t82k5m4z3n8ngs3nuwgudt0h5m8gt348vqwr4y8
    lastmodified: "2026-07-17T20:17:08Z"
    mac: ENC[AES256_GCM,data:zBuxhU6fvDpUo4/8cKcrPO/XU60RC8hFqW+ifiaUiza/6/cJOW9vlY5he/kB7vgG3DsXo6BwZT9Ea3QnovSY+zJhvvL+5aOlIxsA+0MHfF3/QuGMjaU998VeyOpI1s2qX1+W7f+uLDNR25tYkTfuUI5Q2QikmjHy/I+pZsXlNDU=,iv:tPO+ZPq2OAlK1oBvEDw0SzHQqLze0am0FsAIcA/OvXI=,tag:oD1hMNP8/n6knf5gyktSWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
